// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: share/p2p/shrexnd/pb/share.proto

package share_p2p_shrex_nd

import (
	fmt "fmt"
	pb "github.com/celestiaorg/nmt/pb"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_INVALID   StatusCode = 0
	StatusCode_OK        StatusCode = 1
	StatusCode_NOT_FOUND StatusCode = 2
	StatusCode_INTERNAL  StatusCode = 3
)

var StatusCode_name = map[int32]string{
	0: "INVALID",
	1: "OK",
	2: "NOT_FOUND",
	3: "INTERNAL",
}

var StatusCode_value = map[string]int32{
	"INVALID":   0,
	"OK":        1,
	"NOT_FOUND": 2,
	"INTERNAL":  3,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed9f13149b0de397, []int{0}
}

type GetSharesByNamespaceRequest struct {
	Height    uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Namespace []byte `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	FromRow   uint32 `protobuf:"varint,3,opt,name=fromRow,proto3" json:"fromRow,omitempty"`
	ToRow     uint32 `protobuf:"varint,4,opt,name=toRow,proto3" json:"toRow,omitempty"`
}

func (m *GetSharesByNamespaceRequest) Reset()         { *m = GetSharesByNamespaceRequest{} }
func (m *GetSharesByNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*GetSharesByNamespaceRequest) ProtoMessage()    {}
func (*GetSharesByNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9f13149b0de397, []int{0}
}
func (m *GetSharesByNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSharesByNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetSharesByNamespaceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetSharesByNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSharesByNamespaceRequest.Merge(m, src)
}
func (m *GetSharesByNamespaceRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetSharesByNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSharesByNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSharesByNamespaceRequest proto.InternalMessageInfo

func (m *GetSharesByNamespaceRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *GetSharesByNamespaceRequest) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *GetSharesByNamespaceRequest) GetFromRow() uint32 {
	if m != nil {
		return m.FromRow
	}
	return 0
}

func (m *GetSharesByNamespaceRequest) GetToRow() uint32 {
	if m != nil {
		return m.ToRow
	}
	return 0
}

type GetSharesByNamespaceStatusResponse struct {
	Status StatusCode `protobuf:"varint,1,opt,name=status,proto3,enum=share.p2p.shrex.nd.StatusCode" json:"status,omitempty"`
}

func (m *GetSharesByNamespaceStatusResponse) Reset()         { *m = GetSharesByNamespaceStatusResponse{} }
func (m *GetSharesByNamespaceStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetSharesByNamespaceStatusResponse) ProtoMessage()    {}
func (*GetSharesByNamespaceStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9f13149b0de397, []int{1}
}
func (m *GetSharesByNamespaceStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetSharesByNamespaceStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetSharesByNamespaceStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetSharesByNamespaceStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSharesByNamespaceStatusResponse.Merge(m, src)
}
func (m *GetSharesByNamespaceStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetSharesByNamespaceStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSharesByNamespaceStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSharesByNamespaceStatusResponse proto.InternalMessageInfo

func (m *GetSharesByNamespaceStatusResponse) GetStatus() StatusCode {
	if m != nil {
		return m.Status
	}
	return StatusCode_INVALID
}

type NamespaceRowResponse struct {
	Shares [][]byte  `protobuf:"bytes,1,rep,name=shares,proto3" json:"shares,omitempty"`
	Proof  *pb.Proof `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *NamespaceRowResponse) Reset()         { *m = NamespaceRowResponse{} }
func (m *NamespaceRowResponse) String() string { return proto.CompactTextString(m) }
func (*NamespaceRowResponse) ProtoMessage()    {}
func (*NamespaceRowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed9f13149b0de397, []int{2}
}
func (m *NamespaceRowResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NamespaceRowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NamespaceRowResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NamespaceRowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceRowResponse.Merge(m, src)
}
func (m *NamespaceRowResponse) XXX_Size() int {
	return m.Size()
}
func (m *NamespaceRowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceRowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceRowResponse proto.InternalMessageInfo

func (m *NamespaceRowResponse) GetShares() [][]byte {
	if m != nil {
		return m.Shares
	}
	return nil
}

func (m *NamespaceRowResponse) GetProof() *pb.Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func init() {
	proto.RegisterEnum("share.p2p.shrex.nd.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*GetSharesByNamespaceRequest)(nil), "share.p2p.shrex.nd.GetSharesByNamespaceRequest")
	proto.RegisterType((*GetSharesByNamespaceStatusResponse)(nil), "share.p2p.shrex.nd.GetSharesByNamespaceStatusResponse")
	proto.RegisterType((*NamespaceRowResponse)(nil), "share.p2p.shrex.nd.NamespaceRowResponse")
}

func init() { proto.RegisterFile("share/p2p/shrexnd/pb/share.proto", fileDescriptor_ed9f13149b0de397) }

var fileDescriptor_ed9f13149b0de397 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xe3, 0x40,
	0x18, 0xc6, 0x33, 0xfd, 0x93, 0x6e, 0xdf, 0xfe, 0xd9, 0x30, 0x94, 0x12, 0x76, 0x97, 0x10, 0x02,
	0x0b, 0x61, 0x0f, 0x09, 0x64, 0xc1, 0xa3, 0xd0, 0x5a, 0x95, 0x62, 0x49, 0x65, 0xda, 0x7a, 0x12,
	0x24, 0xb1, 0x53, 0xe3, 0xa1, 0x99, 0x31, 0x93, 0x52, 0x3d, 0xfb, 0x05, 0xfc, 0x58, 0x1e, 0x7b,
	0xf4, 0x28, 0xed, 0x17, 0x91, 0x4c, 0x52, 0x7b, 0xd0, 0x5b, 0x9e, 0x27, 0xbf, 0x79, 0xe6, 0x7d,
	0xde, 0x01, 0x53, 0x44, 0x41, 0x42, 0x5d, 0xee, 0x71, 0x57, 0x44, 0x09, 0x7d, 0x8c, 0xe7, 0x2e,
	0x0f, 0x5d, 0x69, 0x3a, 0x3c, 0x61, 0x29, 0xc3, 0xb8, 0x10, 0x1e, 0x77, 0x24, 0xe1, 0xc4, 0xf3,
	0x5f, 0x6d, 0x1e, 0xba, 0x3c, 0x61, 0x6c, 0x91, 0x33, 0xd6, 0x33, 0x82, 0xdf, 0xe7, 0x34, 0x9d,
	0x64, 0xa4, 0xe8, 0x3f, 0xf9, 0xc1, 0x92, 0x0a, 0x1e, 0xdc, 0x52, 0x42, 0x1f, 0x56, 0x54, 0xa4,
	0xb8, 0x0b, 0x6a, 0x44, 0xef, 0xef, 0xa2, 0x54, 0x47, 0x26, 0xb2, 0x2b, 0xa4, 0x50, 0xf8, 0x0f,
	0xd4, 0xe3, 0x3d, 0xab, 0x97, 0x4c, 0x64, 0x37, 0xc9, 0xc1, 0xc0, 0x3a, 0xd4, 0x16, 0x09, 0x5b,
	0x12, 0xb6, 0xd6, 0xcb, 0x26, 0xb2, 0x5b, 0x64, 0x2f, 0x71, 0x07, 0xaa, 0x29, 0xcb, 0xfc, 0x8a,
	0xf4, 0x73, 0x61, 0x5d, 0x83, 0xf5, 0xdd, 0x10, 0x93, 0x34, 0x48, 0x57, 0x82, 0x50, 0xc1, 0x59,
	0x2c, 0x28, 0x3e, 0x02, 0x55, 0x48, 0x47, 0xce, 0xd2, 0xf6, 0x0c, 0xe7, 0x6b, 0x41, 0x27, 0x3f,
	0x73, 0xc2, 0xe6, 0x94, 0x14, 0xb4, 0x35, 0x83, 0xce, 0xa1, 0x17, 0x5b, 0x7f, 0xe6, 0x75, 0x41,
	0x95, 0x01, 0x59, 0x5e, 0xd9, 0x6e, 0x92, 0x42, 0xe1, 0xbf, 0x50, 0x95, 0x2b, 0x92, 0xbd, 0x1a,
	0xde, 0x4f, 0xa7, 0x58, 0x58, 0xe8, 0x5c, 0x66, 0x1f, 0x24, 0xff, 0xfb, 0xef, 0x18, 0xe0, 0x70,
	0x19, 0x6e, 0x40, 0x6d, 0xe8, 0x5f, 0xf5, 0x46, 0xc3, 0x81, 0xa6, 0x60, 0x15, 0x4a, 0xe3, 0x0b,
	0x0d, 0xe1, 0x16, 0xd4, 0xfd, 0xf1, 0xf4, 0xe6, 0x6c, 0x3c, 0xf3, 0x07, 0x5a, 0x09, 0x37, 0xe1,
	0xc7, 0xd0, 0x9f, 0x9e, 0x12, 0xbf, 0x37, 0xd2, 0xca, 0x7d, 0xfd, 0x75, 0x6b, 0xa0, 0xcd, 0xd6,
	0x40, 0xef, 0x5b, 0x03, 0xbd, 0xec, 0x0c, 0x65, 0xb3, 0x33, 0x94, 0xb7, 0x9d, 0xa1, 0x84, 0xaa,
	0x7c, 0x9b, 0xff, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x43, 0xb4, 0x09, 0x76, 0xe3, 0x01, 0x00,
	0x00,
}

func (m *GetSharesByNamespaceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSharesByNamespaceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSharesByNamespaceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ToRow != 0 {
		i = encodeVarintShare(dAtA, i, uint64(m.ToRow))
		i--
		dAtA[i] = 0x20
	}
	if m.FromRow != 0 {
		i = encodeVarintShare(dAtA, i, uint64(m.FromRow))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Namespace) > 0 {
		i -= len(m.Namespace)
		copy(dAtA[i:], m.Namespace)
		i = encodeVarintShare(dAtA, i, uint64(len(m.Namespace)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintShare(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GetSharesByNamespaceStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetSharesByNamespaceStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetSharesByNamespaceStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintShare(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NamespaceRowResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NamespaceRowResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NamespaceRowResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Proof != nil {
		{
			size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintShare(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Shares) > 0 {
		for iNdEx := len(m.Shares) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Shares[iNdEx])
			copy(dAtA[i:], m.Shares[iNdEx])
			i = encodeVarintShare(dAtA, i, uint64(len(m.Shares[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintShare(dAtA []byte, offset int, v uint64) int {
	offset -= sovShare(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GetSharesByNamespaceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovShare(uint64(m.Height))
	}
	l = len(m.Namespace)
	if l > 0 {
		n += 1 + l + sovShare(uint64(l))
	}
	if m.FromRow != 0 {
		n += 1 + sovShare(uint64(m.FromRow))
	}
	if m.ToRow != 0 {
		n += 1 + sovShare(uint64(m.ToRow))
	}
	return n
}

func (m *GetSharesByNamespaceStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovShare(uint64(m.Status))
	}
	return n
}

func (m *NamespaceRowResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Shares) > 0 {
		for _, b := range m.Shares {
			l = len(b)
			n += 1 + l + sovShare(uint64(l))
		}
	}
	if m.Proof != nil {
		l = m.Proof.Size()
		n += 1 + l + sovShare(uint64(l))
	}
	return n
}

func sovShare(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozShare(x uint64) (n int) {
	return sovShare(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GetSharesByNamespaceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShare
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSharesByNamespaceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSharesByNamespaceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShare
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShare
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShare
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShare
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = append(m.Namespace[:0], dAtA[iNdEx:postIndex]...)
			if m.Namespace == nil {
				m.Namespace = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromRow", wireType)
			}
			m.FromRow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShare
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FromRow |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToRow", wireType)
			}
			m.ToRow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShare
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ToRow |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipShare(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShare
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetSharesByNamespaceStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShare
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetSharesByNamespaceStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetSharesByNamespaceStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShare
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= StatusCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipShare(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShare
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NamespaceRowResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowShare
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NamespaceRowResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NamespaceRowResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shares", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShare
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthShare
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthShare
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Shares = append(m.Shares, make([]byte, postIndex-iNdEx))
			copy(m.Shares[len(m.Shares)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowShare
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthShare
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthShare
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proof == nil {
				m.Proof = &pb.Proof{}
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipShare(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthShare
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipShare(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowShare
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShare
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowShare
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthShare
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupShare
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthShare
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthShare        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowShare          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupShare = fmt.Errorf("proto: unexpected end of group")
)
