run:
  timeout: 5m

linters:
  enable:
    - bidichk
    - bodyclose
     # - depguard as of v1.54.2, the default config throws errors on our repo
    - dogsled
    - dupl
    - errcheck
    - errorlint
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    - exportloopref
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    # - gocyclo
    # - godox
    - gofmt
    - gofumpt
    - goimports
    # - golint - deprecated since v1.41. revive will be used instead
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - interfacer
    - lll
    - loggercheck
    - misspell
    # - maligned
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - protogetter
    # - scopelint - deprecated since v1.39. exportloopref will be used instead
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    # - unparam
    - unused
    # - whitespace
    # - wsl
    # - gocognit
    - wastedassign
    - whitespace
    - nolintlint
    - asciicheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - revive
    - linters:
        - lll
      source: "https://"
  max-same-issues: 50

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/celestiaorg/celestia-node
  dupl:
    threshold: 200
  gofumpt:
    extra-rules: true
