global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'celestia-node'
    static_configs:
      - targets: ['bridge-0-TestBlobMetricsTestSuite:8890']
    metrics_path: '/metrics'
    scrape_interval: 5s
