package testnet

import (
	"github.com/celestiaorg/knuu/pkg/errors"
)

type Error = errors.Error

var (
	ErrEmptyInstanceName                                 = errors.New("EmptyInstanceName", "instance name is empty")
	ErrInvalidNodeType                                   = errors.New("InvalidNodeType", "invalid node type")
	ErrEmptyVersion                                      = errors.New("EmptyVersion", "version is empty")
	ErrEmptyChainID                                      = errors.New("EmptyChainID", "chain id is empty")
	ErrEmptyGenesisHash                                  = errors.New("EmptyGenesisHash", "genesis hash is empty")
	ErrEmptyExecutor                                     = errors.New("EmptyExecutor", "executor is empty")
	ErrEmptyConsensus                                    = errors.New("EmptyConsensus", "consensus is empty")
	ErrExecutorNotSet                                    = errors.New("ExecutorNotSet", "executor is not set")
	ErrConsensusNotSet                                   = errors.New("ConsensusNotSet", "consensus is not set")
	ErrEmptyAppIP                                        = errors.New("EmptyAppIP", "app ip is empty")
	ErrFailedToGetStatus                                 = errors.New("FailedToGetStatus", "failed to get status")
	ErrFailedToUnmarshalStatus                           = errors.New("FailedToUnmarshalStatus", "failed to unmarshal status")
	ErrFailedToGetResultFromStatus                       = errors.New("FailedToGetResultFromStatus", "failed to get result from status")
	ErrFailedToGetNodeInfoFromStatus                     = errors.New("FailedToGetNodeInfoFromStatus", "failed to get node info from status")
	ErrFailedToGetNetworkFromNodeInfo                    = errors.New("FailedToGetNetworkFromNodeInfo", "failed to get network from node info")
	ErrFailedToGetErrorDataFromStatus                    = errors.New("FailedToGetErrorDataFromStatus", "failed to get error data from status")
	ErrFailedToGetIdFromNodeInfo                         = errors.New("FailedToGetIdFromNodeInfo", "failed to get id from node info")
	ErrFailedToGetHashFromBlockId                        = errors.New("FailedToGetHashFromBlockId", "failed to get hash from block id")
	ErrFailedToGetLatestBlockHeight                      = errors.New("FailedToGetLatestBlockHeight", "failed to get latest block height")
	ErrFailedToConvertLatestBlockHeightToInt             = errors.New("FailedToConvertLatestBlockHeightToInt", "failed to convert latest block height to int")
	ErrFailedToUnmarshalBlock                            = errors.New("FailedToUnmarshalBlock", "failed to unmarshal block")
	ErrFailedToGetResultFromBlock                        = errors.New("FailedToGetResultFromBlock", "failed to get result from block")
	ErrFailedToGetBlockIdFromBlock                       = errors.New("FailedToGetBlockIdFromBlock", "failed to get block id from block")
	ErrFailedToGetSyncInfoFromStatus                     = errors.New("FailedToGetSyncInfoFromStatus", "failed to get sync info from status")
	ErrFailedToGetLatestBlockHeightFromSyncInfo          = errors.New("FailedToGetLatestBlockHeightFromSyncInfo", "failed to get latest block height from sync info")
	ErrFailedToConvertLatestBlockHeightFromSyncInfoToInt = errors.New("FailedToConvertLatestBlockHeightFromSyncInfoToInt", "failed to convert latest block height from sync info to int")
	ErrFailedToGetValidatorIP                            = errors.New("FailedToGetValidatorIP", "failed to get validator ip")
	ErrFailedToGetBlock                                  = errors.New("FailedToGetBlock", "failed to get block")
	ErrFailedToGetHashFromBlock                          = errors.New("FailedToGetHashFromBlock", "failed to get hash from block")
	ErrFailedToCreateBridge                              = errors.New("FailedToCreateBridge", "failed to create bridge")
	ErrFailedToCreateNode                                = errors.New("FailedToCreateNode", "failed to create node")
	ErrMetricNotFound                                    = errors.New("MetricNotFound", "metric '%s' not found")
	ErrFailedToFetchPrometheusData                       = errors.New("FailedToFetchPrometheusData", "failed to fetch Prometheus data")
	ErrFailedToParsePrometheusMetrics                    = errors.New("FailedToParsePrometheusMetrics", "failed to parse Prometheus metrics")
	ErrFailedToGetP2PInfo                                = errors.New("FailedToGetP2PInfo", "failed to get p2p info")
	ErrFailedToGetIP                                     = errors.New("FailedToGetIP", "failed to get ip")
	ErrFailedToGetBridgeID                               = errors.New("FailedToGetBridgeID", "failed to get bridge id")
	ErrFailedToUnmarshalP2PInfo                          = errors.New("FailedToUnmarshalP2PInfo", "failed to unmarshal p2p info")
	ErrFailedToGetResultFromP2PInfo                      = errors.New("FailedToGetResultFromP2PInfo", "failed to get result from p2p info")
	ErrFailedToGetIDFromP2PInfo                          = errors.New("FailedToGetIDFromP2PInfo", "failed to get id from p2p info")
	ErrOperationCanceled                                 = errors.New("OperationCanceled", "operation canceled")
)
