{
 "title": "DA Network Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node_id",
    "query": {
     "query": "label_values(testground_das_network_head, exported_instance)"
    }
   },
   {
    "name": "run",
    "query": "show tag values with key = \"run\""
   },
   {
    "name": "square_size",
    "label": "square_size",
    "query": {
     "query": "label_values(testground_das_sample_time_hist_bucket, header_width)"
    }
   },
   { "name": "prom_ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "# Node Alive",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (exported_instance) (testground_head))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sampled Heights",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "testground_das_total_sampled_headers{exported_instance=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Sample Head",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values(\"testground_das_sampled_chain_head\", testground_das_sampled_chain_head{exported_instance=\"$node_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Head",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(testground_head)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# nodes / height",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_values(\"testground_das_sampled_chain_head\", testground_das_sampled_chain_head)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# nodes / das_network_head",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_values(\"testground_das_network_head\", testground_das_network_head)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(Network) Avg  DASing time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate (testground_das_sample_time_hist_sum{failed=\"false\", header_width=~\"$square_size\"}[5m])/rate(testground_das_sample_time_hist_count{failed=\"false\", header_width=~\"$square_size\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of DAS times < 5s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(testground_das_sample_time_hist_bucket{le=\"1\"}[5m])) by (height)\n/\nsum(rate(testground_das_sample_time_hist_count[5m])) by (height)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of DAS times  > 10s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(testground_das_sample_time_hist_bucket{le=\"+Inf\", header_width=~\"$square_size\"}[5m])) by (height) - sum(rate(testground_das_sample_time_hist_bucket{le=\"10\", header_width=~\"$square_size\"}[5m])) by (height))\n/ sum(rate(testground_das_sample_time_hist_count{header_width=\"$square_size\"}[5m])) by (height)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of DAS times < 5s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(testground_das_sample_time_hist_bucket{le=\"5\"}[5m])) by (height)\n/\nsum(rate(testground_das_sample_time_hist_count[5m])) by (height)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of DAS times  in [5s, 10s]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(testground_das_sample_time_hist_bucket{le=\"10\", header_width=~\"$square_size\"}[5m])) by (height) - sum(rate(testground_das_sample_time_hist_bucket{le=\"5\", header_width=~\"$square_size\"}[5m])) by (height))\n/ sum(rate(testground_das_sample_time_hist_count[5m])) by (height)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(Node) Avg DASing time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate (testground_das_sample_time_hist_sum{exported_instance=\"$node_id\", header_width=~\"$square_size\"}[5m])/rate(testground_das_sample_time_hist_count{exported_instance=\"$node_id\", header_width=~\"$square_size\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of Peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "testground_p2p_peer_count{exported_instance=\"$light_node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "(Network) DAS durations (s)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (header, exported_instance) (\n    (rate (testground_das_sample_time_hist_sum{failed=\"false\", header_width=\"$square_size\"}[5m]) != 0)\n    /\n    rate(testground_das_sample_time_hist_count{failed=\"false\", header_width=\"$square_size\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Square Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(testground_node_share_blackbox_eds_size_sum)/2",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EDS Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "testground_node_share_blackbox_eds_size_sum{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 38 },
   "targets": [
    {
     "expr": "(testground_das_total_sampled_headers{exported_instance=\"$node_id\"}/testground_das_network_head{exported_instance=\"$node_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "testground_node_runtime_counter_in_seconds{exported_instance=\"$node_id\"}/(time() - testground_node_start_ts{exported_instance=\"$node_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer ID / height",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "testground_das_sampled_chain_head",
     "legendFormat": "__auto"
    },
    { "expr": "testground_das_network_head", "legendFormat": "__auto" },
    {
     "expr": "testground_total_synced_headers",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Header Transfer Rate (bytes/s)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(testground_node_header_blackbox_request_duration_sum{exported_instance=\"$node_id\"}[$__range])/rate(testground_node_header_blackbox_request_duration_count{exported_instance=\"$node_id\"}[$__range]))/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Share Transfer Rate (bytes/s)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate(testground_node_share_blackbox_request_duration_sum{exported_instance=\"$node_id\"}[5m])/rate(testground_node_share_blackbox_request_duration_count{exported_instance=\"$node_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg OUT BW Rate (bytes/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "testground_p2p_bandwidth_rate_outbound_sum{exported_instance=\"$node_id\"}/testground_p2p_bandwidth_rate_outbound_count{exported_instance=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg IN BW Rate (bytes/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "testground_p2p_bandwidth_rate_inbound_sum{exported_instance=\"$node_id\"}/testground_p2p_bandwidth_rate_inbound_count{exported_instance=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total OUT BW",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "testground_p2p_bandwidth_total_outbound_sum{exported_instance=\"$node_id\"}/testground_p2p_bandwidth_total_outbound_count{exported_instance=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total IN BW",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "testground_p2p_bandwidth_total_inbound_sum{exported_instance=\"$node_id\"}/testground_p2p_bandwidth_total_inbound_count{exported_instance=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total OUT BW by Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "testground_p2p_total_outbound_by_peer_sum{exported_instance=\"$node_id\"}/testground_p2p_total_outbound_by_peer_count{exported_instance=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total IN BW by Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "testground_p2p_total_inbound_by_peer_sum{exported_instance=\"$node_id\"}/testground_p2p_total_inbound_by_peer_count{exported_instance=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block time per Height",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "avg by (height) (\n  rate (testground_node_header_blackbox_block_time_sum{exported_instance=\"$node_id\"}[5m])\n  /\n  rate(testground_node_header_blackbox_block_time_count{exported_instance=\"$node_id\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}