package das

import (
	"context"

	"github.com/celestiaorg/celestia-node/das"
)

// API is a wrapper around Module for the RPC.
// TODO(@distractedm1nd): These structs need to be autogenerated.
type API struct {
	SamplingStats func(ctx context.Context) (das.SamplingStats, error)
}

type Module interface {
	SamplingStats(ctx context.Context) (das.SamplingStats, error)
}
