// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: share/proof/pb/proof.proto

package proof

import (
	fmt "fmt"
	pb "github.com/celestiaorg/nmt/pb"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type IncompleteRowsProof struct {
	FirstIncompleteRowProof *pb.Proof `protobuf:"bytes,1,opt,name=firstIncompleteRowProof,proto3" json:"firstIncompleteRowProof,omitempty"`
	LastIncompleteRowProof  *pb.Proof `protobuf:"bytes,2,opt,name=lastIncompleteRowProof,proto3" json:"lastIncompleteRowProof,omitempty"`
}

func (m *IncompleteRowsProof) Reset()         { *m = IncompleteRowsProof{} }
func (m *IncompleteRowsProof) String() string { return proto.CompactTextString(m) }
func (*IncompleteRowsProof) ProtoMessage()    {}
func (*IncompleteRowsProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_568df82aaa36537b, []int{0}
}
func (m *IncompleteRowsProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IncompleteRowsProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IncompleteRowsProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IncompleteRowsProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncompleteRowsProof.Merge(m, src)
}
func (m *IncompleteRowsProof) XXX_Size() int {
	return m.Size()
}
func (m *IncompleteRowsProof) XXX_DiscardUnknown() {
	xxx_messageInfo_IncompleteRowsProof.DiscardUnknown(m)
}

var xxx_messageInfo_IncompleteRowsProof proto.InternalMessageInfo

func (m *IncompleteRowsProof) GetFirstIncompleteRowProof() *pb.Proof {
	if m != nil {
		return m.FirstIncompleteRowProof
	}
	return nil
}

func (m *IncompleteRowsProof) GetLastIncompleteRowProof() *pb.Proof {
	if m != nil {
		return m.LastIncompleteRowProof
	}
	return nil
}

type DataRootProof struct {
	SquareSize  int64                `protobuf:"varint,1,opt,name=squareSize,proto3" json:"squareSize,omitempty"`
	RowsProof   *IncompleteRowsProof `protobuf:"bytes,2,opt,name=rowsProof,proto3" json:"rowsProof,omitempty"`
	MerkleProof *MerkleProof         `protobuf:"bytes,3,opt,name=merkleProof,proto3" json:"merkleProof,omitempty"`
}

func (m *DataRootProof) Reset()         { *m = DataRootProof{} }
func (m *DataRootProof) String() string { return proto.CompactTextString(m) }
func (*DataRootProof) ProtoMessage()    {}
func (*DataRootProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_568df82aaa36537b, []int{1}
}
func (m *DataRootProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataRootProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DataRootProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DataRootProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRootProof.Merge(m, src)
}
func (m *DataRootProof) XXX_Size() int {
	return m.Size()
}
func (m *DataRootProof) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRootProof.DiscardUnknown(m)
}

var xxx_messageInfo_DataRootProof proto.InternalMessageInfo

func (m *DataRootProof) GetSquareSize() int64 {
	if m != nil {
		return m.SquareSize
	}
	return 0
}

func (m *DataRootProof) GetRowsProof() *IncompleteRowsProof {
	if m != nil {
		return m.RowsProof
	}
	return nil
}

func (m *DataRootProof) GetMerkleProof() *MerkleProof {
	if m != nil {
		return m.MerkleProof
	}
	return nil
}

type MerkleProof struct {
	Total        int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Start        int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End          int64    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	SubtreeRoots [][]byte `protobuf:"bytes,4,rep,name=subtreeRoots,proto3" json:"subtreeRoots,omitempty"`
}

func (m *MerkleProof) Reset()         { *m = MerkleProof{} }
func (m *MerkleProof) String() string { return proto.CompactTextString(m) }
func (*MerkleProof) ProtoMessage()    {}
func (*MerkleProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_568df82aaa36537b, []int{2}
}
func (m *MerkleProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MerkleProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MerkleProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MerkleProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerkleProof.Merge(m, src)
}
func (m *MerkleProof) XXX_Size() int {
	return m.Size()
}
func (m *MerkleProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MerkleProof.DiscardUnknown(m)
}

var xxx_messageInfo_MerkleProof proto.InternalMessageInfo

func (m *MerkleProof) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *MerkleProof) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *MerkleProof) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *MerkleProof) GetSubtreeRoots() [][]byte {
	if m != nil {
		return m.SubtreeRoots
	}
	return nil
}

func init() {
	proto.RegisterType((*IncompleteRowsProof)(nil), "proof.IncompleteRowsProof")
	proto.RegisterType((*DataRootProof)(nil), "proof.DataRootProof")
	proto.RegisterType((*MerkleProof)(nil), "proof.MerkleProof")
}

func init() { proto.RegisterFile("share/proof/pb/proof.proto", fileDescriptor_568df82aaa36537b) }

var fileDescriptor_568df82aaa36537b = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0xcd, 0x7c, 0xf3, 0x55, 0xf0, 0xa6, 0xfe, 0x30, 0x8a, 0x86, 0x2c, 0x86, 0x92, 0x55, 0x57,
	0x29, 0xa8, 0x0b, 0xd7, 0x22, 0x48, 0x17, 0x82, 0x8c, 0x4f, 0x30, 0xd1, 0x29, 0x16, 0xd3, 0x4e,
	0x9c, 0xb9, 0x45, 0xf0, 0x29, 0x7c, 0x03, 0xd7, 0xbe, 0x89, 0xcb, 0x2e, 0x5d, 0x4a, 0xf2, 0x22,
	0x92, 0xc9, 0x48, 0x13, 0x48, 0x77, 0x73, 0xcf, 0x39, 0xf7, 0xdc, 0x73, 0x18, 0x88, 0xed, 0x93,
	0x34, 0x6a, 0x52, 0x18, 0xad, 0x67, 0x93, 0x22, 0x6b, 0x1e, 0x69, 0x61, 0x34, 0x6a, 0x36, 0x70,
	0x43, 0xbc, 0xdf, 0x85, 0x93, 0x4f, 0x02, 0x47, 0xd3, 0xe5, 0x83, 0x5e, 0x14, 0xb9, 0x42, 0x25,
	0xf4, 0xab, 0xbd, 0xab, 0x59, 0x36, 0x85, 0xd3, 0xd9, 0xdc, 0x58, 0xec, 0x70, 0x8e, 0x8a, 0xc8,
	0x88, 0x8c, 0xc3, 0xb3, 0x83, 0xd4, 0xdb, 0x64, 0xa9, 0x83, 0xc5, 0x36, 0x3d, 0xbb, 0x81, 0x93,
	0x5c, 0xf6, 0x3a, 0xfd, 0xeb, 0x77, 0xda, 0x22, 0x4f, 0x3e, 0x08, 0xec, 0x5d, 0x4b, 0x94, 0x42,
	0x6b, 0x6c, 0xac, 0x39, 0x80, 0x7d, 0x59, 0x49, 0xa3, 0xee, 0xe7, 0x6f, 0xca, 0x05, 0xa3, 0xa2,
	0x85, 0xb0, 0x4b, 0xd8, 0x35, 0x7f, 0x95, 0xfc, 0xb5, 0xd8, 0x5f, 0xeb, 0x29, 0x2d, 0x36, 0x62,
	0x76, 0x01, 0xe1, 0x42, 0x99, 0xe7, 0x5c, 0x35, 0xbb, 0xd4, 0xed, 0x32, 0xbf, 0x7b, 0xbb, 0x61,
	0x44, 0x5b, 0x96, 0x68, 0x08, 0x5b, 0x1c, 0x3b, 0x86, 0x01, 0x6a, 0x94, 0xb9, 0x4f, 0xd6, 0x0c,
	0x35, 0x6a, 0x51, 0x1a, 0x74, 0x81, 0xa8, 0x68, 0x06, 0x76, 0x08, 0x54, 0x2d, 0x1f, 0xdd, 0x21,
	0x2a, 0xea, 0x27, 0x4b, 0x60, 0x68, 0x57, 0x19, 0x1a, 0xa5, 0xea, 0xc2, 0x36, 0xfa, 0x3f, 0xa2,
	0xe3, 0xa1, 0xe8, 0x60, 0x57, 0xd1, 0x57, 0xc9, 0xc9, 0xba, 0xe4, 0xe4, 0xa7, 0xe4, 0xe4, 0xbd,
	0xe2, 0xc1, 0xba, 0xe2, 0xc1, 0x77, 0xc5, 0x83, 0x6c, 0xc7, 0xfd, 0xef, 0xf9, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x6f, 0x93, 0x9a, 0x7d, 0x14, 0x02, 0x00, 0x00,
}

func (m *IncompleteRowsProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IncompleteRowsProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IncompleteRowsProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastIncompleteRowProof != nil {
		{
			size, err := m.LastIncompleteRowProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProof(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.FirstIncompleteRowProof != nil {
		{
			size, err := m.FirstIncompleteRowProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProof(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DataRootProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataRootProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataRootProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MerkleProof != nil {
		{
			size, err := m.MerkleProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProof(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.RowsProof != nil {
		{
			size, err := m.RowsProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProof(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.SquareSize != 0 {
		i = encodeVarintProof(dAtA, i, uint64(m.SquareSize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MerkleProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MerkleProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MerkleProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SubtreeRoots) > 0 {
		for iNdEx := len(m.SubtreeRoots) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SubtreeRoots[iNdEx])
			copy(dAtA[i:], m.SubtreeRoots[iNdEx])
			i = encodeVarintProof(dAtA, i, uint64(len(m.SubtreeRoots[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.End != 0 {
		i = encodeVarintProof(dAtA, i, uint64(m.End))
		i--
		dAtA[i] = 0x18
	}
	if m.Start != 0 {
		i = encodeVarintProof(dAtA, i, uint64(m.Start))
		i--
		dAtA[i] = 0x10
	}
	if m.Total != 0 {
		i = encodeVarintProof(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintProof(dAtA []byte, offset int, v uint64) int {
	offset -= sovProof(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IncompleteRowsProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FirstIncompleteRowProof != nil {
		l = m.FirstIncompleteRowProof.Size()
		n += 1 + l + sovProof(uint64(l))
	}
	if m.LastIncompleteRowProof != nil {
		l = m.LastIncompleteRowProof.Size()
		n += 1 + l + sovProof(uint64(l))
	}
	return n
}

func (m *DataRootProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SquareSize != 0 {
		n += 1 + sovProof(uint64(m.SquareSize))
	}
	if m.RowsProof != nil {
		l = m.RowsProof.Size()
		n += 1 + l + sovProof(uint64(l))
	}
	if m.MerkleProof != nil {
		l = m.MerkleProof.Size()
		n += 1 + l + sovProof(uint64(l))
	}
	return n
}

func (m *MerkleProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Total != 0 {
		n += 1 + sovProof(uint64(m.Total))
	}
	if m.Start != 0 {
		n += 1 + sovProof(uint64(m.Start))
	}
	if m.End != 0 {
		n += 1 + sovProof(uint64(m.End))
	}
	if len(m.SubtreeRoots) > 0 {
		for _, b := range m.SubtreeRoots {
			l = len(b)
			n += 1 + l + sovProof(uint64(l))
		}
	}
	return n
}

func sovProof(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProof(x uint64) (n int) {
	return sovProof(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IncompleteRowsProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProof
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IncompleteRowsProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IncompleteRowsProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstIncompleteRowProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FirstIncompleteRowProof == nil {
				m.FirstIncompleteRowProof = &pb.Proof{}
			}
			if err := m.FirstIncompleteRowProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastIncompleteRowProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastIncompleteRowProof == nil {
				m.LastIncompleteRowProof = &pb.Proof{}
			}
			if err := m.LastIncompleteRowProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProof(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProof
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataRootProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProof
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataRootProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataRootProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SquareSize", wireType)
			}
			m.SquareSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SquareSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowsProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RowsProof == nil {
				m.RowsProof = &IncompleteRowsProof{}
			}
			if err := m.RowsProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MerkleProof == nil {
				m.MerkleProof = &MerkleProof{}
			}
			if err := m.MerkleProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProof(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProof
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MerkleProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProof
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MerkleProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MerkleProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			m.Start = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Start |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field End", wireType)
			}
			m.End = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.End |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubtreeRoots", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubtreeRoots = append(m.SubtreeRoots, make([]byte, postIndex-iNdEx))
			copy(m.SubtreeRoots[len(m.SubtreeRoots)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProof(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProof
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProof(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProof
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProof
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProof
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProof
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProof
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProof
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProof        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProof          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProof = fmt.Errorf("proto: unexpected end of group")
)
