name: Create Release Tracking Epic

# This workflow creates an EPIC in the devops repo and notifies the devops team
# on slack for tracking the deployment of a release to testnets and mainnet.
on:
  release:
    types: [released]
jobs:
  trigger_issue:
    uses: celestiaorg/.github/.github/workflows/reusable_create_release_tracking_epic.yml@v0.4.5
    secrets: inherit
    with:
      release-repo: ${{ github.repository }}
      release-version: ${{ github.event.release.tag_name }}
